### ISSUE TITLE
URLInput is not an allowed input element

### ISSUE THREAD

**Issue by MaartenStaa** [nicklambourne/slackblocks#101]
When constructing an `InputBlock` with an `element` of type `URLInput`, an `InvalidUsageError` is raised:

```python
from slackblocks import URLInput, InputBlock

block = InputBlock(
    label="My label",
    element=URLInput(
        action_id="some-action", placeholder="Enter a URL"
    ),
)
```

```
  File ".venv/lib/python3.12/site-packages/slackblocks/blocks.py", line 338, in __init__
    raise InvalidUsageError("")
slackblocks.errors.InvalidUsageError
```

It seems `URLInput` is missing in the list of `ALLOWED_INPUT_ELEMENTS` in `slackblocks/blocks.py`. Additionally, a better error message here would be great.

**Comment by nicklambourne** [comment]
Fixed in `v1.0.12`, thanks for letting me know! https://pypi.org/project/slackblocks/1.0.12/
