### ISSUE TITLE
Resolve function is called for every key

### ISSUE THREAD

**Issue by zaawee** [nicklambourne/slackblocks#17]
Hey,

I'm using the message class and I noticed that `__get__` is implemented using resolve in order to get each value,
this means that when `**message` is used the message is resolved once for the keys method and then again for every key.

I found it better to just use `**message._resolve()` this way a dictionary is returned and `_resolve` is called once.

I think making resolve a public function can be a great option to solve this issue.

**Comment by nicklambourne** [comment]
Hey, you're exactly right. My focus with this package was the user experience more than the performance. That said, I know it's far less than ideal, so until I work out a clever way to fix this I've implemented `to_dict()` on `Message` which is just a public `_resolve()` so if people are concerned about performance they can just use `**message.to_dict()`. Hope this helps :)

**Comment by zaawee** [comment]
Thanks! that sounds like a great solution.
