### ISSUE TITLE
SectionBlock should maybe make the text input optional

### ISSUE THREAD

**Issue by palewire** [nicklambourne/slackblocks#22]
I have been able to submit section blocks to the Slack API with only fields, and no text attribute. I don't think your class allows that. I propose making the input optional. If you agree, I'd be happy to submit a patch.

https://github.com/nicklambourne/slackblocks/blob/8668a011dc8a04023b85adbd2adb0647a1befb48/slackblocks/blocks.py#L53-L81

**Comment by nicklambourne** [comment]
Hey @palewire, apologies for it taking so long but I finally found the time to rip out the broken TravisCI release infrastructure and move it all to GitHub Actions. The newly released `v0.3.1` includes the functionality from your PR.
