### ISSUE TITLE
SectionBlock text doesn't allow null or none 

### ISSUE THREAD

**Issue by pankajmalhotra** [nicklambourne/slackblocks#31]
I need to pass null value for text=None, but I am getting error that empty or null string are not allowed.
But in the code it is optional
SectionBlock( fields=[Text(text="version", type_=TextType.PLAINTEXT))

def __init__(
        self,
        text: Optional[TextLike] = None,
        block_id: Optional[str] = None,
        fields: Optional[List[Text]] = None,
        accessory: Optional[Element] = None,
    ):
    
    
    Version installed 0.9.6

**Comment by nicklambourne** [comment]
Thanks for bringing this up, have fixed in https://github.com/nicklambourne/slackblocks/releases/tag/v0.9.7
