### ISSUE TITLE
ModalView contains extra field submit_disabled, needs to be removed

### ISSUE THREAD

**Issue by nikhilascendo** [nicklambourne/slackblocks#36]
SlackClientError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] failed to match all allowed schemas [json-pointer:/view]', '[ERROR] invalid additional property: submit_disabled [json-pointer:/view]']}}")

**Comment by nicklambourne** [comment]
Hey @nikhilascendo, apologies for the delay in following up. Can you please share a minimal example that triggers this so I can reproduce the issue on my end?
