### ISSUE TITLE
Cannot use EmailInput inside InputBlock

### ISSUE THREAD

**Issue by nikhilascendo** [nicklambourne/slackblocks#40]
<img width="261" alt="image" src="https://github.com/nicklambourne/slackblocks/assets/141814334/05e592e5-c10d-4a4b-b501-9d78d8a4dd32">

EmailInput missing in list of ALLOWED_INPUT_ELEMENTS

Check fails at this point 
<img width="578" alt="image" src="https://github.com/nicklambourne/slackblocks/assets/141814334/c0c1a766-0968-49b5-8b7d-aba731d98def">

**Comment by nicklambourne** [comment]
Not missing, it's not actually supported according to the spec. See: https://api.slack.com/reference/block-kit/blocks#input_fields. You can probably accomplish what you're after with a PlainTextInput, no?
