### ISSUE TITLE
Cannot create UserSelectMenu object with placeholder=None

### ISSUE THREAD

**Issue by mmasior-clgx** [nicklambourne/slackblocks#42]
UserSelectMenu requires only one positional argument: 'action_id' but when:
slackblocks.UserSelectMenu('action')
then
self.placeholder = Text.to_text(
                       ^^^^^^^^^^^^^
    raise InvalidUsageError("This field cannot have the value None or ''")
slackblocks.errors.InvalidUsageError: This field cannot have the value None or ''

**Comment by nicklambourne** [comment]
Should be fixed in `v0.9.11`, thanks for catching this.
