### ISSUE TITLE
How to use Button Element?

### ISSUE THREAD

**Issue by thosieucoi** [nicklambourne/slackblocks#5]
Dear @nicklambourne 

I have tried

`SectionBlock(text="For Test Button",accessory=Button(action_id="1", text="Choose"))`

But got error

`The server responded with: {'ok': False, 'error': 'invalid_blocks', 'response_metadata': {'messages': ['[ERROR] must be a valid enum value ...`

It worked fine without _accessory_

`SectionBlock(text="For Test Button")`

Would you please guide me how to generate button?
Thank you so much.

**Comment by thosieucoi** [comment]
Fixed in https://github.com/nicklambourne/slackblocks/pull/6
Please review.

**Comment by nicklambourne** [comment]
Closed in #6
