### ISSUE TITLE
Slack Client requires a dict for publishing views

### ISSUE THREAD

**Issue by victorneo** [nicklambourne/slackblocks#52]
Slack's official web client requires a `dict[Unknown, Unknown]` when publishing views, and would not work unless I am calling the private `_resolve()` method when using `HomeTabView`.

```
v = HomeTabView(...)
client.views_publish(..., view=v._resolve())
```

I have noticed that you have added a `to_dict()` method in #17 so I am wondering if it's okay to do the same for Views.

If that is okay with you, I'll be happy to submit a small PR to add it for Views.

**Comment by nicklambourne** [comment]
Hey Victor, thanks for pointing this out (and for the offer of a PR!), I've rolled the feature into the latest release: https://github.com/nicklambourne/slackblocks/releases/tag/v0.9.13.
