### ISSUE TITLE
75 chars limitation on Text Fields.

### ISSUE THREAD

**Issue by kigsmtua** [nicklambourne/slackblocks#53]
According to the docs here, https://api.slack.com/reference/block-kit/composition-objects#text looks like this field has a limitation of 3000 however this implementation has capped this at 75. Is there a reason I might have missed

I wouldn't mind pushing a quick fix for this

**Comment by nicklambourne** [comment]
Hey @kigsmtua, probably some legacy field validation based on a past state of their API. Happy to push through a fix, but I noticed you'd closed this as completed already?

**Comment by kigsmtua** [comment]
@nicklambourne I believe I  closed this by mistake

**Comment by nicklambourne** [comment]
Where did you see the 75 char limit in the codebase? At the time the issue was opened the Text object itself had no length limit but I've subsequently added validation checks for a 3000 char max.

**Comment by kigsmtua** [comment]
https://github.com/nicklambourne/slackblocks/blob/master/slackblocks/objects.py#L205-L207 this actually passed in the option object as a 75 char limit, since the description is a text, it should allow upto the max I believe

**Comment by nicklambourne** [comment]
> https://github.com/nicklambourne/slackblocks/blob/master/slackblocks/objects.py#L205-L207 this actually passed in the option object as a 75 char limit, since the description is a text, it should allow upto the max I believe

The documentation on the `Option` object from the Slack Blocks API reference lists the limit explicitly:
> Maximum length for the text within this field is 75 characters.

So I'm still a bit confused as to what you mean.

Source: https://api.slack.com/reference/block-kit/composition-objects#:~:text=overflow%20menu.-,Maximum%20length%20for%20the,within%20this%20field%20is%2075%20characters.,-No
