### ISSUE TITLE
Feature request: Add support for rich_text block types and its supported object types

### ISSUE THREAD

**Issue by rileydakota** [nicklambourne/slackblocks#61]
Thoughts on adding support for https://api.slack.com/reference/block-kit/blocks#rich_text to slackblocks? Happy to cut a PR but would need a little help understanding the best way to implement it given its nested object nature.

**Comment by nicklambourne** [comment]
Sounds like a great idea. Let me have a crack at it this weekend and get back to you 👌

**Comment by nicklambourne** [comment]
Let me know what you think when you get a chance: https://github.com/nicklambourne/slackblocks/pull/62 :)

**Comment by nicklambourne** [comment]
This has been merged in the latest release: https://pypi.org/project/slackblocks/0.9.16/

**Comment by rileydakota** [comment]
Amazing! Somehow this slipped past me! Thank you so much, going to take this for a spin!
