### ISSUE TITLE
Question: Supported way to use slackblocks with WebhookClient

### ISSUE THREAD

**Issue by rileydakota** [nicklambourne/slackblocks#68]
Hello!

We have a few slack apps that rely on app based incoming webhooks. We utilize the [WebhookClient](https://github.com/slackapi/python-slack-sdk/blob/7e71b7377a9f0e627f0da45fd5a74fe6117b7cbc/slack_sdk/webhook/client.py#L28) class in the SDK to interface with this. It doesn't require a few of the fields, like channel or text. Is there a supported way to pass the blocks in (aside from dropping them into a Message instance and grabbing the blocks from that?)

**Comment by nicklambourne** [comment]
There isn't currently, but I'd be open to making something like a `WebhookMessage` class with just those required fields. Would that suit your use case? (Also happy to take other suggestions on board).

**Comment by nicklambourne** [comment]
Added in #70 / `v1.0.3`, let me know if anything is broken / can be improved.
