### ISSUE TITLE
`elements.Image`: `alt_text` argument shouldn't be required 

### ISSUE THREAD

**Issue by fedirz** [nicklambourne/slackblocks#75]
I feel like the `alt_text` argument should be made optional, with a default value being `" "`, the same way it's done in `ImageBlock`.

If this change will be welcome, I'd like to make a pull-request implementing it.

**Comment by nicklambourne** [comment]
Sounds good to me, more than happy to support a PR.

**Comment by nicklambourne** [comment]
Fix will roll out in v1.0.7, thanks for pointing this out! 🚀
