### ISSUE TITLE
RIchTextList and nested RIchText issues

### ISSUE THREAD

**Issue by liviuf-ancas** [nicklambourne/slackblocks#80]
Hello, i am trying to create this block : 

`{
	"blocks": [
		{
			"type": "divider"
		},
		{
			"type": "rich_text",
			"elements": [
				{
					"type": "rich_text_section",
					"elements": [
						{
							"type": "text",
							"text": "10:00 - Lorem ipsum blaba\n"
						}
					]
				},
				{
					"type": "rich_text_list",
					"style": "bullet",
					"indent": 0,
					"border": 0,
					"elements": [
						{
							"type": "rich_text_section",
							"elements": [
								{
									"type": "text",
									"text": "10:00 - Lorem ipsum two "
								},
								{
									"type": "emoji",
									"name": "white_check_mark",
									"unicode": "2705"
								},
								{
									"type": "text",
									"text": " "
								}
							]
						},
						{
							"type": "rich_text_section",
							"elements": [
								{
									"type": "text",
									"text": "10:01 - lorem ipsum 3! "
								},
								{
									"type": "emoji",
									"name": "white_check_mark",
									"unicode": "2705"
								},
								{
									"type": "text",
									"text": " "
								}
							]
						}
					]
				}
			]
		},
		{
			"type": "divider"
		}
	]
}`

I am trying like this: 

`
status = RichTextSection([
        RichText(text="10;00 - Lorem ipsum blaba\n", bold=True),
        RichTextList(style="bullet", elements=(
            RichTextSection([
                RichText("10:00 - Lorem ipsum two \n"),
                RichText("10:01 - Lorem ipsum3!\n"),
            ])
        ))
        ])
`

and i get the following error 

`} (<class 'slackblocks.rich_text.objects.RichTextList'>)) inconsistent with expected type (<class 'slackblocks.rich_text.elements.RichTextChannel'>, <class 'slackblocks.rich_text.elements.RichTextEmoji'>, <class 'slackblocks.rich_text.elements.RichTextLink'>, <class 'slackblocks.rich_text.elements.RichText'>, <class 'slackblocks.rich_text.elements.RichTextUser'>, <class 'slackblocks.rich_text.elements.RichTextUserGroup'>).`

I have no idea how to fix this? Can anyone help me? 

Thanks

**Comment by nicklambourne** [comment]
[According to the docs](https://api.slack.com/reference/block-kit/blocks#rich_text_section) you can't put a `RichTextList` inside a `RichTextSection` which is what that code is doing.

I assume what you're after is closer to something like:
```python
block = RichTextBlock(
    elements=[
        RichText(text="10;00 - Lorem ipsum blaba\n", bold=True),
        RichTextList(
            style="bullet", 
            elements=[
                RichTextSection(RichText("10:00 - Lorem ipsum two \n"),
                RichTextSection(RichText("10:01 - Lorem ipsum3!\n")),
    ]
)
```
