### ISSUE TITLE
ContextBlock elements arg has the wrong type

### ISSUE THREAD

**Issue by rizenfrmtheashes** [nicklambourne/slackblocks#86]
In the ContextBlock init, the elements arg might have the wrong type. 

I think it's currently `elements: Optional[List[Union[Element, CompositionObjectType]]] = None,`
but I think `CompositionObjectType` should be `CompositionObject`.

Because `CompositionObjectType` refers to the enum type, but the `CompositionObject` refers to the actual element/object. 

Here's the typeerror being thrown, and `Text` should be subclassing `CompositionObject`

![Screenshot 2024-04-23 at 10 23 28 AM](https://github.com/nicklambourne/slackblocks/assets/2954959/07e9cddd-8f8c-4e52-974b-c14ba62cedb9)
![Screenshot 2024-04-23 at 10 23 42 AM](https://github.com/nicklambourne/slackblocks/assets/2954959/929e7d9d-74ad-4988-9fd0-dab653438602)

**Comment by K8sKween** [comment]
It seems like it should be the ABC CompositionObject. Would you like to be the one to raise a PR? Otherwise I can try to get a change and some test pushed this week.

**Comment by nicklambourne** [comment]
Thanks for catching this, will push out a release with the fix ASAP.
