### ISSUE TITLE
[Documentation] Multiple broken links on docs homepage

### ISSUE THREAD

**Issue by K8sKween** [nicklambourne/slackblocks#89]
Currently on the homepage of the docs: https://nicklambourne.github.io/slackblocks/latest/ under the section "Messages" the hyperlink on the text "Messages" currently goes to a dead end of "https://nicklambourne.github.io/reference/messages/"

This should be updated to "https://nicklambourne.github.io/slackblocks/latest/reference/messages/"

There are many components like this such as:
Messages: https://nicklambourne.github.io/reference/messages/
Blocks: https://nicklambourne.github.io/reference/blocks
Elements: https://nicklambourne.github.io/reference/elements
Objects: https://nicklambourne.github.io/reference/objects
Text: https://nicklambourne.github.io/reference/objects/#objects.Text

There are more, but they all just need to have the `{{version}}` added, typically `latest`

**Comment by K8sKween** [comment]
I think this might be a issue more core to links than just the homepage, on the messages page https://nicklambourne.github.io/slackblocks/latest/reference/messages/ the link to `Blocks` in "a list of Blocks..." needs the version tag as well.

**Comment by nicklambourne** [comment]
I think this has all been fixed in the docs for the latest release. Let me know if I've missed any.

**Comment by K8sKween** [comment]
Did a quick round of testing, everything looks good to me. Thanks for fixing it all @nicklambourne !
